### PR TITLE
Mark end of options to /bin/sh with "--"

### PR DESCRIPTION
**Pull request by link2xt**
Otherwise the command starting with -- may
be treated as an option by /bin/sh

### CODE REVIEW

**Comment by link2xt** [comment]
Lack of "--" caused undecipherable error message for me recently: https://github.com/deltachat/deltachat-desktop-dev-env/issues/11

**Comment by vweevers** [comment]
Will android's shell accept this?

**Comment by link2xt** [comment]
> Will android's shell accept this?

It should according to POSIX, but it is better to test this.

I think Android uses `mksh` and it works for me:
```
$ mksh -c -- "echo ok"
ok
```

**Comment by mafintosh** [comment]
Not on expert on android, but 👍 otherwise from me.

**Comment by vweevers** [comment]
4.1.1

**Pull request merged**
