### PR TITLE
Search name

### LINKED ISSUE #22: The loading algorithm doesn't work for bundled applications.
When using Webpack to bundle a Node application into a single .js file, node-gyp-build cannot unambiguously load the correct `.node` file.

In a bundled application, Webpack can provide as `__dirname` either `"/"` which is the default, the input file's path relative to the build context, or Node's regular behaviour

To support `bindings` based native modules, you can copy the built `.node` files into `build/Release` relative to the bundle file, because bindings is passed the name of the .node file. When `node-gyp-build` tries to load build files from that folder, if it contains multiple `.node` files from multiple modules, it will grab the first one in it for every module that uses `node-gyp-build`.

E.g. if my project uses `argon2` and `leveldown` and builds them from source, I will have the bundled output structure:

```
foo
|-- index.js
|-- build
    |-- Release
        |-- argon2.node
        |-- leveldown.node
```

but either library trying to load its bindings file will just end up loading `argon2.node`.

---

For similar reasons prebuilds are completely impossible to use, because all flavours of prebuild for a given runtime and ABI will have the same filename (such as `node-napi.node`), and since there's only one bundle file its containing directory won't disambiguate between them.

### PR DESCRIPTION
**Pull request by aminya**
Try to fix #22 

This uses old JavaScript syntax. I am not sure why but it seems you want to support very old JavaScript.

### CODE REVIEW

**Comment by aminya** [comment]
@mafintosh I am blocked on this. If you can solve the issue it would be nice.

**Comment by mafintosh** [comment]
Unsure what is blocked and what the feature does.

**Comment by aminya** [comment]
The goal is to provide a `name` as the second argument, and the script searches for that package if it was not in the first argument:
```
var binding = require('node-gyp-build')(__dirname, "my-native-module")
```

**Comment by vweevers** [comment]
@aminya Can you provide an example? What is the expected directory structure?

Lack of namespacing (other than by node_modules/xyz) is a known problem (https://github.com/prebuild/node-gyp-build/pull/27) but I'm not sure how this PR solves it or that it covers all cases.

**Comment by aminya** [comment]
> @aminya Can you provide an example? What is the expected directory structure?
> 
> Lack of namespacing (other than by node_modules/xyz) is a known problem (#27) but I'm not sure how this PR solves it or that it covers all cases.

You can't put `index.js` anywhere else other than the root of the repository. Builders change the `__dirname` of a file when they are built. For example, the `src` code is written to `dist`.


Here is an example. Try to move `index.js` to `src` folder, set the `main` to `dist`, and build the code. Everything breaks.
https://github.com/atom-ide-community/fuzzaldrin-plus-fast

**Comment by mafintosh** [comment]
I don't think that belongs here. The node-gyp-build interface tells you to pass in the directory where the prebuilds folder is, thats the contract.

**Comment by vweevers** [comment]
> Here is an example. Try to move index.js to src folder, set the main to dist, and build the code. Everything breaks.
https://github.com/atom-ide-community/fuzzaldrin-plus-fast

Simple solution: create an `/index.js` entry point that does `module.exports = require('./dist/')(__dirname)`.

**Pull request closed without merging**
